// Typed user profile module for Caner.
//
// This mirrors the structured facts captured in context/notes/user-profile.md
// and context/notes/relocation-constraints.md. It is the canonical runtime
// representation of the person whose situation drives every personalised
// explainer in src/explainers/.
//
// Keep in sync with the upstream notes when the underlying facts change
// (visa status, employment, upfront capacity, etc.). Do NOT edit this file
// to reflect in-flight deliberation — only resolved, durable facts.

export interface UserProfile {
  id: string;
  preferred_name: string;
  age: number;
  nationality: string;
  visa_type: "uk-graduate" | "uk-skilled-worker" | "uk-citizen" | "other";
  visa_expires: string; // ISO date
  has_uk_credit_history: boolean;
  has_uk_payslips: boolean;
  has_uk_guarantor: boolean;
  current_rent_monthly: number; // GBP
  current_bills_monthly: number; // GBP
  current_total_monthly: number; // GBP
  current_area: string;
  max_upfront_months: number;
  preferred_bedroom_count: 0 | 1 | 2; // 0 = studio
  cooks_regularly: boolean;
  trains_seriously: boolean;
  reads_heavily: boolean;
  noise_tolerance: "low" | "medium" | "high";
  preferred_age_cohort: "18-29" | "30-39";
}

export const caner: UserProfile = {
  id: "caner",
  preferred_name: "Caner",
  age: 24,
  nationality: "Turkish",
  visa_type: "uk-graduate",
  visa_expires: "2027-08-01",
  has_uk_credit_history: false,
  has_uk_payslips: false,
  has_uk_guarantor: false,
  current_rent_monthly: 2500,
  current_bills_monthly: 500,
  current_total_monthly: 3000,
  current_area: "Ten Degrees, Croydon",
  max_upfront_months: 3,
  preferred_bedroom_count: 1,
  cooks_regularly: true,
  trains_seriously: true,
  reads_heavily: true,
  noise_tolerance: "low",
  preferred_age_cohort: "18-29",
};
